concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker"
  url = "http://100.68.32.90:8080/"
  id = 7
  token = "glrtr-Dv2VACMYdXg46bJhNBCeLm86MQpwOjEKdDozCw.01.121vf3k9r"
  token_obtained_at = 2025-10-25T12:28:42Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "node:20"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = [
      "/cache",
      "/home/ntdotjsx/DevOps-Lab/www:/var/www/html",
      "/var/run/docker.sock:/var/run/docker.sock"
    ]
    shm_size = 0
    network_mtu = 0